version: "3.9"

services:
  postgres:
    image: postgres:13.3
    container_name: cparser-postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - cparser

  clickhouse-zookeeper:
      image: zookeeper
      ports:
          - "2181:2181"
          - "2182:2182"
      container_name: clickhouse-zookeeper
      hostname: clickhouse-zookeeper
      networks:
      - clickhouse-net

  clickhouse-01:
      image: yandex/clickhouse-server
      hostname: clickhouse-01
      container_name: clickhouse-01
      ports:
          - 9001:9000
      volumes:
              - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
              - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
              - ./config/macros/macros-01.xml:/etc/clickhouse-server/config.d/macros.xml
              - ./config/users.xml:/etc/clickhouse-server/users.xml
              # - ./data/server-01:/var/lib/clickhouse
      ulimits:
          nofile:
              soft: 262144
              hard: 262144
      depends_on:
          - "clickhouse-zookeeper"
      networks:
            - clickhouse-net

  clickhouse-02:
      image: yandex/clickhouse-server
      hostname: clickhouse-02
      container_name: clickhouse-02
      ports:
          - 9002:9000
      volumes:
              - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
              - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
              - ./config/macros/macros-02.xml:/etc/clickhouse-server/config.d/macros.xml
              - ./config/users.xml:/etc/clickhouse-server/users.xml
              # - ./data/server-02:/var/lib/clickhouse
      ulimits:
          nofile:
              soft: 262144
              hard: 262144
      depends_on:
          - "clickhouse-zookeeper"
      networks:
            - clickhouse-net


  clickhouse-03:
      image: yandex/clickhouse-server
      hostname: clickhouse-03
      container_name: clickhouse-03
      ports:
          - 9003:9000
      volumes:
              - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
              - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
              - ./config/macros/macros-03.xml:/etc/clickhouse-server/config.d/macros.xml
              - ./config/users.xml:/etc/clickhouse-server/users.xml
              # - ./data/server-03:/var/lib/clickhouse
      ulimits:
          nofile:
              soft: 262144
              hard: 262144
      depends_on:
          - "clickhouse-zookeeper"
      networks:
        - clickhouse-net

  clickhouse-04:
      image: yandex/clickhouse-server
      hostname: clickhouse-04
      container_name: clickhouse-04
      ports:
          - 9004:9000
      volumes:
              - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.xml
              - ./config/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
              - ./config/macros/macros-04.xml:/etc/clickhouse-server/config.d/macros.xml
              - ./config/users.xml:/etc/clickhouse-server/users.xml
              # - ./data/server-04:/var/lib/clickhouse
      ulimits:
          nofile:
              soft: 262144
              hard: 262144
      depends_on:
          - "clickhouse-zookeeper"
      networks:
        - clickhouse-net
 
networks:
  clickhouse-net:    
  cparser: